In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
import os

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
from PIL import Image
from tempfile import TemporaryDirectory
from torchsummary import summary

from model_preprocessing import CustomModel, data_pipeline, train_model

In [125]:
data_transforms = {
    'train': transforms.Compose([
        transforms.Resize((32, 32)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'test': transforms.Compose([
        transforms.Resize((32, 32)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

In [126]:
data_dir = "D:\\1_Магистратура_ВШЭ\\1_AI_YP24_Team_61\\Deepfake-Classification\\app\\data\\cifake-real-and-ai-generated-synthetic-images"
image_datasets_logreg = {x: datasets.ImageFolder(os.path.join(data_dir, x),
                                                 data_transforms[x]
                                                 ) for x in ['train', 'test']}

In [127]:
evens = list(range(0, len(image_datasets_logreg['train']), 2))
train_dataset = torch.utils.data.Subset(image_datasets_logreg['train'], evens)

evens = list(range(0, len(image_datasets_logreg['test']), 2))
test_dataset = torch.utils.data.Subset(image_datasets_logreg['test'], evens)

train_loader = torch.utils.data.DataLoader(train_dataset, 
										   batch_size=512,
										   shuffle=True, 
										   num_workers=0, 
										   pin_memory=True)

test_loader = torch.utils.data.DataLoader(test_dataset, 
										   batch_size=512,
										   shuffle=True, 
										   num_workers=0, 
										   pin_memory=True)

In [138]:
train_dataset[0][0].shape

torch.Size([3, 32, 32])

In [129]:
dataset_sizes = {x: len(train_dataset) if x == 'train' else len(test_dataset) for x in ['train', 'test']}

In [130]:
dataset_sizes

{'train': 50000, 'test': 10000}

In [ ]:
dataset_sizes = {x: len(image_datasets_logreg[x]) for x in ['train', 'test']}

In [28]:
image_datasets_logreg['train'].classes

['FAKE', 'REAL']

In [69]:
image_datasets_logreg['train'].class_to_idx

{'FAKE': 0, 'REAL': 1}

In [73]:
lst = [i for i in range(len(image_datasets_logreg['train'])) if image_datasets_logreg['train'][i][1] == 0]

In [76]:
lst[-1]

49999

# Пробуем сделать inference готовой моделью и сделать пайплайн трансформации одного изображения

In [225]:
import numpy as np
from sklearn.model_selection import train_test_split
import os

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
from PIL import Image
from tempfile import TemporaryDirectory
from torchsummary import summary

from model_preprocessing import CustomModel, data_pipeline, train_model

In [229]:
model = CustomModel()
print(model)

model_path = f"D:\\1_Магистратура_ВШЭ\\1_AI_YP24_Team_61\\Deepfake-Classification\\app\\backend\\model_weights\\string.pt"
model.load_state_dict(torch.load(model_path, weights_only=True))
print(model)
model.eval()

#im = Image.open(r"..\data\inference_image\1.webp")
im = Image.open(r"..\data\inference_image\3.jpg")

CustomModel(
  (model): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_r

In [231]:
def foo():
	return [1, 2]

foo()

[1, 2]

In [219]:
transform = transforms.Compose([
	transforms.Resize((32, 32)),
    transforms.ToTensor(),
    #transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

In [220]:
transform = transforms.Compose([
	transforms.Resize((32, 32)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

im_tensor = transform(im)
im_tensor = im_tensor.reshape(-1, 3, 32, 32)
im_tensor = im_tensor.cuda()

In [221]:
im_tensor.shape

torch.Size([1, 3, 32, 32])

In [222]:
#plt.imshow(im_tensor.permute(1, 2, 0))

In [223]:
pred = model(im_tensor)
[float(pred[-1][-1]), float(pred[-1][-1]) > 0.6]

[0.8659921884536743, True]

In [ ]:
data_transforms = {
    'train': transforms.Compose([
        transforms.Resize((32, 32)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
    'test': transforms.Compose([
        transforms.Resize((32, 32)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ]),
}

In [224]:
type(im_tensor)

torch.Tensor

In [ ]:
import torch
from torchvision.transforms import v2

H, W = 32, 32
img = torch.randint(0, 256, size=(3, H, W), dtype=torch.uint8)

transforms = v2.Compose([
    v2.RandomResizedCrop(size=(224, 224), antialias=True),
    v2.RandomHorizontalFlip(p=0.5),
    v2.ToDtype(torch.float32, scale=True),
    v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])
img = transforms(img)

# EDA

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
import scienceplots
import sys
import torch
import torchvision
import cv2

from contextlib import nullcontext
from functools import partialmethod
from pprint import pp
from pytorch_grad_cam import AblationCAM
from pytorch_grad_cam.utils.model_targets import ClassifierOutputTarget
from pytorch_grad_cam.utils.image import show_cam_on_image
from sklearn.metrics import ConfusionMatrixDisplay
from torch import nn, optim
from torchvision import transforms
from torchvision.datasets import ImageFolder
from torch.utils.data.dataloader import DataLoader
from tqdm import tqdm

plt.rcParams["font.family"] = "serif"

In [14]:
widths = []
heights = []
for i_split in ['train', 'test']: # произведем замеры всех изображения (на train и test)
    if i_split == 'train':
        len_train = len(data[i_split])
    else:
        len_test = len(data[i_split])
    for i_img in tqdm(data[i_split]):
        image = i_img[0]
        image = torch.permute(image, (1, 2, 0))
        widths.append(image.shape[0]) # заносим в список параметры широты всех изображений
        heights.append(image.shape[1]) # заносим в список параметры широты всех изображений  

100%|██████████| 20000/20000 [00:04<00:00, 4339.60it/s]


In [13]:
(np.array(widths[:len_train]) * np.array(heights[:len_train])).sum()

np.int64(102400000)

In [10]:
cntTrain

102400000

In [19]:
# тензоры для хранения прокси-информации по RGB каналам
tsum = torch.tensor([0.0, 0.0, 0.0])
tsum_sq = torch.tensor([0.0, 0.0, 0.0])
cntTrain = (np.array(widths[:len_train]) * np.array(heights[:len_train])).sum() # количество пикселей в выборке

for i_img in tqdm(data['train']):
    tsum += i_img[0].sum(axis=(1, 2))
    tsum_sq += (i_img[0]**2).sum(axis=(1, 2))
    
mean_rgb = tsum / cntTrain
var_rgb = (tsum_sq / cntTrain) - (mean_rgb**2) # E(X^2) - E^2(X)
std_rgb = torch.sqrt(var_rgb)

100%|██████████| 100000/100000 [00:25<00:00, 3972.96it/s]


In [20]:
mean_rgb, var_rgb, std_rgb

(tensor([0.4720, 0.4629, 0.4178]),
 tensor([0.0564, 0.0564, 0.0707]),
 tensor([0.2376, 0.2374, 0.2659]))

In [18]:
mean_rgb, var_rgb, std_rgb

(tensor([0.4720, 0.4629, 0.4178]),
 tensor([0.0564, 0.0564, 0.0707]),
 tensor([0.2376, 0.2374, 0.2659]))

In [4]:
from torchvision import datasets, models, transforms

In [26]:
def calc_min_max_size(data):
    widths = []
    heights = []
    for i_split in ['train', 'test']: # произведем замеры всех изображения (на train и test)
        if i_split == 'train':
            len_train = len(data[i_split])
        else:
            len_test = len(data[i_split])
        for i_img in tqdm(data[i_split]):
            image = i_img[0]
            image = torch.permute(image, (1, 2, 0))
            widths.append(image.shape[0]) # заносим в список параметры широты всех изображений
            heights.append(image.shape[1]) # заносим в список параметры широты всех изображений 

    # Делаем расчет средних, минимальных и максимальных размеров изображений
    array_sizes = np.multiply(widths, heights) # Создаем массив всех размеров (width*heights)
    avg_size = np.mean(array_sizes)
    min_size = np.min(array_sizes)
    max_size = np.max(array_sizes)

    return avg_size, min_size, max_size, widths, heights, len_train, len_test

def calc_mean_std(data, widths, heights, segment, len_train, len_test):
    # тензоры для хранения прокси-информации по RGB каналам
    tsum = torch.tensor([0.0, 0.0, 0.0])
    tsum_sq = torch.tensor([0.0, 0.0, 0.0])
    if segment == 'train':
        cntTrain = (np.array(widths[:len_train]) * np.array(heights[:len_train])).sum() # количество пикселей в выборке
    if segment == 'test':
        cntTrain = (np.array(widths[len_test:]) * np.array(heights[len_test:])).sum() # количество пикселей в выборке

    for i_img in tqdm(data['train']):
        tsum += i_img[0].sum(axis=(1, 2))
        tsum_sq += (i_img[0]**2).sum(axis=(1, 2))
        
    mean_rgb = tsum / cntTrain
    var_rgb = (tsum_sq / cntTrain) - (mean_rgb**2) # E(X^2) - E^2(X)
    std_rgb = torch.sqrt(var_rgb)

    return mean_rgb, var_rgb, std_rgb

def target_hist(data):
    dct_targetHist = {}

    for i_split in ['train', 'test']:
        cnt_fake = 0
        cnt_real = 0
        for _, target in tqdm(data[i_split]):
            if target == 1:
                cnt_real += 1
            elif target == 0: 
                cnt_fake += 1
        dct_targetHist[i_split] = dct_targetHist.get(i_split, {'fake': cnt_fake, 
                                                            'real': cnt_real})
    return dct_targetHist

def make_eda():
    # Предварительная загрузка и трансформация данных из локальной папки на ПК
    data = {
        # Создаем словарь, где по ключу train/test будут лежать соответствующие данные
        # По очереди обращаемся к папкам train/test, чтобы загрузить оттуда данные
        split: datasets.ImageFolder(
            # Если путь f"{DATASET_DIR}/{split}" содержит другие папки, то названия этих папок устанавливаются в качестве
            # классов (LABELS) для данных в папке f"{DATASET_DIR}/{split}".
            # Узнать метки классов можно с помощью вызова data['train'].classes
            fr"..\data\dataset_example\{split}",
            #
            transform=transforms.Compose(
                [
                    transforms.ToTensor(),
                ]
            ),
            #target_transform=TargetMapper(LABELS),
        )
        for split in ['train', 'test']
    }
    print("Данные загружены!")
    # Считаем средний, минимальный и максимальный размер изображений во всем датасете
    avg_size, min_size, max_size, widths, heights, len_train, len_test = calc_min_max_size(data)
    # Считаем mean/std в разрезе train/test
    mean_rgb_train, var_rgb_train, std_rgb_train = calc_mean_std(data, widths, heights, 'train', len_train, len_test)
    mean_rgb_test, var_rgb_test, std_rgb_test = calc_mean_std(data, widths, heights, 'test', len_train, len_test)
    dct_targetHist = target_hist(data)

    return {'avg_size': avg_size, 
            'min_size': min_size, 
            'max_size': max_size,
            'mean_rgb_train': mean_rgb_train, 
            'var_rgb_train': var_rgb_train, 
            'std_rgb_train': std_rgb_train, 
            'mean_rgb_test': mean_rgb_test, 
            'var_rgb_test': var_rgb_test, 
            'std_rgb_test': std_rgb_test,
            'dct_targetHist': dct_targetHist}

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import os

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
from PIL import Image
from tempfile import TemporaryDirectory
from torchsummary import summary

from model_preprocessing import CustomModel, data_pipeline, train_model
from tqdm import tqdm

In [2]:
# Предварительная загрузка и трансформация данных из локальной папки на ПК
data = {
    # Создаем словарь, где по ключу train/test будут лежать соответствующие данные
    # По очереди обращаемся к папкам train/test, чтобы загрузить оттуда данные
    split: datasets.ImageFolder(
        # Если путь f"{DATASET_DIR}/{split}" содержит другие папки, то названия этих папок устанавливаются в качестве
        # классов (LABELS) для данных в папке f"{DATASET_DIR}/{split}".
        # Узнать метки классов можно с помощью вызова data['train'].classes
        fr"..\data\dataset_example\{split}",
        #
        transform=transforms.Compose(
            [
                transforms.ToTensor(),
            ]
        )
    )
    for split in ['train', 'test']
}

print("Данные загружены!")

Данные загружены!


In [3]:
def calculate_statistics(data):
	dct_targetHist = {}
	for i_split in ['train', 'test']:
		if i_split == 'train':
			len_train = len(data[i_split])
		else:
			len_test = len(data[i_split])
		# Тензоры для хранения прокси-информации по RGB каналам
		tsum = torch.tensor([0.0, 0.0, 0.0])
		tsum_sq = torch.tensor([0.0, 0.0, 0.0])
		# Переменные для расчета числа наблюдений в каждом классе
		cnt_fake = 0
		cnt_real = 0
		# Инициализируем списки для расчета статистик по размерам
		widths = []
		heights =[]
		for image, target in tqdm(data[i_split]):
			# Прокси-расчеты для вычисления статистики по размерам изобрежений
			image_sz = torch.permute(image, (1, 2, 0))
			widths.append(image_sz.shape[0]) # заносим в список параметры широты всех изображений
			heights.append(image_sz.shape[1]) # заносим в список параметры широты всех изображений
			# Прокси-расчеты для вычисления статистики по mean/std
			tsum += image.sum(axis=(1, 2))
			tsum_sq += (image**2).sum(axis=(1, 2))
			# Считаем число экземпляров каждого класса в разрезе train/test
			if target == 1:
				cnt_real += 1
			elif target == 0: 
				cnt_fake += 1
		if i_split == 'train':
			cntPixels = (np.array(widths) * np.array(heights)).sum() # количество пикселей в выборке
		elif i_split == 'test':
			cntPixels = (np.array(widths) * np.array(heights)).sum() # количество пикселей в выборке
		# Считаем статистики по размерам изображений
		array_sizes = np.multiply(widths, heights) # Создаем массив всех размеров (width*heights)
		avg_size = np.mean(array_sizes)
		min_size = np.min(array_sizes)
		max_size = np.max(array_sizes)
		# Считаем mean/std в разрезе каждого класса
		mean_rgb = tsum / cntPixels
		var_rgb = (tsum_sq / cntPixels) - (mean_rgb**2) # E(X^2) - E^2(X)
		std_rgb = torch.sqrt(var_rgb)
		dct_targetHist[i_split] = dct_targetHist.get(i_split, 
												{
													'fake_cnt': cnt_fake,
													'real_cnt': cnt_real,
													'avg_size': float(avg_size),
													'min_size': float(min_size),
													'max_size': float(max_size),
													'mean_rgb': mean_rgb.tolist(),
													'var_rgb': var_rgb.tolist(),
													'std_rgb': std_rgb.tolist()
													})
	return dct_targetHist

In [4]:
tt = calculate_statistics(data)

100%|██████████| 20000/20000 [00:04<00:00, 4012.91it/s]


In [5]:
df = pd.DataFrame(tt)

In [9]:
dft = df.T.copy()

In [17]:
dft['mean_red'] = dft['mean_rgb'].apply(lambda x: x[0])
dft['mean_green'] = dft['mean_rgb'].apply(lambda x: x[1])
dft['mean_blue'] = dft['mean_rgb'].apply(lambda x: x[2])

dft['std_red'] = dft['std_rgb'].apply(lambda x: x[0])
dft['std_green'] = dft['std_rgb'].apply(lambda x: x[1])
dft['std_blue'] = dft['std_rgb'].apply(lambda x: x[2])

In [16]:
dft[['fake_cnt', 'real_cnt', 'avg_size', 'min_size', 'max_size', 'mean_red', 'mean_green', 'mean_blue', 'std_red', 'std_green', 'std_blue']].T

train      test
fake_cnt       50000     10000
real_cnt       50000     10000
avg_size      1024.0    1024.0
min_size      1024.0    1024.0
max_size      1024.0    1024.0
mean_red    0.471996  0.473014
mean_green  0.462891  0.463721
mean_blue   0.417822  0.418606

In [14]:
dft.columns

Index(['fake_cnt', 'real_cnt', 'avg_size', 'min_size', 'max_size', 'mean_rgb',
       'var_rgb', 'std_rgb', 'mean_red', 'mean_green', 'mean_blue'],
      dtype='object')